application: thonking-slash-command
module: default
version: prod
runtime: python27
api_version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 3
  min_pending_latency: 100ms
  max_pending_latency: 1000ms
  max_concurrent_requests: 7

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: "2.7.11"

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*/dev_data/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*_test\.py[co]?$

includes:
- handlers.yaml